AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for VPC creation



Resources:
  
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: OlenaVPC


  MyInstanceSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref MyVPC
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''